# Generated by Django 5.2 on 2025-04-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trackinglocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingLocation',
        ),
    ]
