# Generated by Django 5.2 on 2025-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackinglocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Driver_Delivered', 'Delivered by Driver'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
