# Generated by Django 5.2 on 2025-04-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('start_address', models.CharField(blank=True, max_length=255, null=True)),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_address', models.CharField(blank=True, max_length=255, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_time_min', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.order')),
            ],
        ),
    ]
