# Generated by Django 5.2 on 2025-04-08 01:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deliveryroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_accepted', 'Order Accepted'), ('driver_assigned', 'Driver Assigned'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
